# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.15.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=4000 >> .env          
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn build

###################################### 추가된 부분 ######################################

      - name: zip file
        run: zip -r demo.zip ./dist ./scripts ./appspec.yml ./.env ./ecosystem.config.js ./package.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./demo.zip s3://zeroeyes-server-build/demo/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name codepipeline-demo-deploy-by-github
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploygroup-codepipeline-by-github
          --s3-location bucket=zeroeyes-server-build,bundleType=zip,key=demo/deploy/demo.zip
